// generated by mBlock5 for mBot
// codes make you happy

/*
	--todo--
	->movement und rotation fertig
	->nur noch bedingungen wann wie gefahren wird
	->move+delay ist autom. coord update dabei
	->rotation beinhaltet schon beides
 ->wenn rotation erledigt: motor dreht so lange, wie liniensensor wieder was erkennt - funktion die nebenbei zeit misst benötigt. 
         -delay funktion überarbeiten bzw coordinaten update auslagern in extra fun
*/

#include <MeMCore.h>
#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>
#include <cmath.h>
#include <vector>

MeLightSensor lightsensor_6(6);
MeDCMotor motor_9(9);
MeDCMotor motor_10(10);
MeLineFollower linefollower_2(2);
MeUltrasonicSensor ultrasonic_3(3);
double currentTime = 0;
double lastTime = 0;
MeIR ir;
MeLEDMatrix ledMtx_1(1);

float k = 0;
const double PI = 3.14159;

struct move_param{
	int forward = 1;
	int backward = 2;
	int turnLeft = 3;
	int turnRight =4;
	int speed=255;
	int engine_speed_coeff = 0; // engine_s_c = n/speed
	float diameter = 0;
	float wheelbase = 0;
};

struct coordinate{
	float x=0;
	float y=0;
	float phi = 0; //start in x
};

struct time{
	float time_start = 0;
	float time_end = 0;
}


//-----vars------
coordinate bot_coord;
move_param bot_param;
rotation_time = time;
translation_time = time;

std::vector<float> coord_list;
coord_list.push_back((0,0)) // coord where first turn is starting
int phi = 2;
bool firstCheck = false;
int lastDir = bot_param.turnRight;
std::string lastDirection = "LEFT"
float timeVal = 0;
bool is_turnig = false;
bool circum_check = false;

//-vars drive middle
float cchecked_phi = 0;
bool rot_90_check = false;
float middle_time = 0;
bool middle_check = false;
float middle_x = 0;
float middle_y = 0;

void move(const int dir, int speed) {
  int leftSpeed = 0;
  int rightSpeed = 0;
  if(dir == 1) {
    leftSpeed = speed;
    rightSpeed = speed;
  } else if(dir == 2) {
    leftSpeed = -speed;
    rightSpeed = -speed;
  } else if(dir == 3) {
    leftSpeed = -speed;
    rightSpeed = speed;
  } else if(dir == 4) {
    leftSpeed = speed;
    rightSpeed = -speed;
  }
  motor_9.run((9) == M1 ? -(leftSpeed) : (leftSpeed));
  motor_10.run((10) == M1 ? -(rightSpeed) : (rightSpeed));
}


void _delay(float seconds, move_param& param, coordinate& coord, bool CoordUpdate) {
  long endTime = millis() + seconds * 1000;
  while(millis() < endTime) _loop();
	//update coord
	if(CoordUpdate){
		coord.x += 2*PI*param.speed*param.engine_speed_coeff*seconds*std::cos(coord.phi)*(param.diameter/2);// s = v*t = 2pi n * t
		coord.y += 2*PI*param.speed*param.engine_speed_coeff*seconds*std::sin(coord.phi)*(param.diameter/2);
	}
}

// for v2.1
void rotate_bot(move_param &param, coordinate & coord, float phi){ // phi in grad
	coord.phi += phi;
	float theta = phi*(PI/180);
	float t = (param.wheelbase*theta)/(param.speed*param.engine_speed_coeff*2*PI*(param.diameter/2)); // t = wb*theta/n*2*pi*r
	if(phi>0){
		move(param.turnLeft, param.speed);
	}if(phi<0){
		move(param.turnRight, param.speed);
	}
	_delay(t, param, coord, false);

}

//for v2.2
void rotate_bot_undefined(move_param &param, std::string direction){ // phi in grad
	if(direction == "LEFT"){
		move(param.turnLeft, param.speed);
	}else if(direction == "RIGHT"){
		move(param.turnRight, param.speed);
	}else{
		return 0
	}

}

void addCoordRot(move_param &param, coordinate& coord, time &tc){
	float t = (tc.time_end-tc.time_start)/1000;
	float phi_ = (t *  param.speed * param.engine_speed_coeff * param.diameter)/ param.wheelbase; //in rad
	coord.phi += phi_;
}

void addCoordTrans(move_param &param, coordinate& coord, time &tc, std::vector<float> &list){
	float t = (tc.time_end-tc.time_start)/1000;
	float delta = PI*param.diameter*param.speed* param.engine_speed_coeff*t//v = 2pirn - v = s/t --> s = v*t = 2pirn*t
	float delta_x = delta*std::cos(coord.phi);
	float delta_y = delta*std::sin(coord.phi);
	coord.x += delta_x; // 
	coord.y += delta_y;
	list.push_back((delta_x, delta_y))
}


double getLastTime(){
  return currentTime = millis() / 1000.0 - lastTime;
}



void setup() {
  ir.begin();
  ledMtx_1.setColorIndex(1);
  ledMtx_1.setBrightness(6);
  
}

/*
---------------------------v2.1-----------------------------------

void _v1_loop() {
		//check distance
		
		if (linefollower_2.readSensors() == 2.000000){ //right side dark
				if(!firstCheck){		//defines start of circum
						firstCheck = true;
				}
				rotate_bot(bot_param, bot_coord, phi);
				lastDir = 1;
		}
		if (linefollower_2.readSensors() == 1.000000){ //left side dark
				if(!firstCheck){		
						firstCheck = true;
				}
				rotate_bot(bot_param, bot_coord, -phi);
				lastDir = -1;
		}
		if (linefollower_2.readSensors() == 3.000000){ //both are dark
				if(!firstCheck){		
						firstCheck = true;
				}
				rotate_bot(bot_param, bot_coord, lastDir*phi);
		}
		move(bot_param.forward, bot_param.speed)			
}
*/
/*
---------------------------v2.2-----------------------------------
*/
void _loop() {
	if (!circum_check){
		//check distance	--> maybe black always between sensors
		if (linefollower_2.readSensors() == 2.000000){ //right side dark
			if (!is_turnig){
				translation_time.time_end = millis();
				addCoordTrans(bot_param, bot_coord, translation_time, coord_list)
				rotation_time.time_start = millis();
				rotate_bot_undefined(bot_param, "LEFT");
				is_turnig = true;
			}
			lastDirection = "LEFT";
		}
		else if (linefollower_2.readSensors() == 1.000000){ //left side dark
			if (!is_turnig){
				translation_time.time_end = millis();
				addCoordTrans(bot_param, bot_coord, translation_time, coord_list)
				rotation_time.time_start = millis();
				rotate_bot_undefined(bot_param, "RIGHT");
				is_turnig = true;
			}
			lastDirection = "RIGHT";
		}
		else if (linefollower_2.readSensors() == 3.000000){ //both are dark
			if (!is_turnig){
				translation_time.time_end = millis();
				addCoordTrans(bot_param, bot_coord, translation_time, coord_list)
				rotation_time.time_start = millis();
				rotate_bot_undefined(bot_param, lastDirection);
				is_turnig = true;
			}

		}else {
			is_turnig = false;
			rotation_time.time_end = millis();
			addCoordRot(bot_param, bot_coord, rotation_time);
			translation_time.time_start = millis();
			move(bot_param.forward, bot_param.speed);			
		}
	}
	if (bot_coord.phi >=2*PI){
		circum_check = true;
		cchecked_phi = bot_coord.phi; //obsoled --> gedacht falls rotate_bot_undefined verwendet wird
		//... corner fit
		//... calc
		//... set middle points
		//... show
		//mabe multiple rounds
	}
	//driving back to middle
	if(circum_check){ //move_param &param, coordinate & coord, float phi
		if (!rot_90_check){ // drehung in mitte
			rot_90_check = true;
			if lastDirection == "LEFT"{ //richtige 90 grad bekommen
				rotate_bot(bot_param, bot_coord, 90);
			}else{
				rotate_bot(bot_param, bot_coord, -90);
			}
		}else if(!middle_check){
			middle_check = true;
			//										speed									  /							hypothenuse --> nearly x-x_middle
			middle_time = (bot_param.speed*bot_param.engine_speed_coeff*PI*bot_param.diameter)/std::sqrt((bot_coord.x - middle_x)*(bot_coord.x - middle_x)+(bot_coord.y-delta_y)*(bot_coord.y-delta_y))
			move(bot_param.forward, bot_param.speed)
			_delay(middle_time)
		}else{
			//--> steht im mittelpunkt ...fläche anzeige
		}
	}
}

void loop() {
  _v2_loop();
}

